### ISSUE TITLE
writeKey visible in segment debugger

### ISSUE THREAD

**Issue by arielectron** [segmentio/analytics-php#127]
Hello.
I see from the segment debugger, in the "raw" tab, that it arrives with the "writeKey" attribute in the body of the message. This is not so in calls that are made from the javascript client. this is a mistake?
Thank you.

**Comment by nd4p90x** [comment]
Yes, this is normal:

- Writekey is embeded by the libraries, among few other things that the library automatically adds to the payload
- Writekey is not secret so this is ok
