### ISSUE TITLE
[Feature] Retry network errors

### ISSUE THREAD

**Issue by lubird** [segmentio/analytics-php#136]
The SDK should have a mechanism to cope with failed data uploads because of intermittent network errors or other issues. The retry strategy should be:

1. Retry network errors (socket timed out, etc.)
1. Retry server errors (HTTP 5xx)
1. Do NOT retry client errors (HTTP 4xx) except HTTP 429

**Comment by nd4p90x** [comment]
This can be marked as "won't fix", the current version supports the retry rules as stated in the issue.  There is also a back-off feature with defaults that match current requirements.
