### ISSUE TITLE
Identify Server-side events as iOS or Android (Amplitude issue)

### ISSUE THREAD

**Issue by butterup** [segmentio/analytics-php#147]
We use Amplitude as a Destination for Segment as our primary tool for Data Analytics as a business.

**Context:**
- We only have two types of users using our app - (1) iOS, (2) Android. We don’t have a web app currently. We want all users to be identified as either iOS or Android at any one time.
- Naturally, we send track events from our server to track server side events. We also send Identify events from the server, as the server is the best source of truth for user properties against a user. 
- On a Server-side Track call, we follow it with an Identify call (this is recommended implementation). The outcome of this is that the “Platform” is set to “Analytics-PHP”, instead of iOS or Android.

**Issue:**
We want to be able to explicitly identify a user as Platform = iOS, or Platform = Android on a Server-side Identify call made from Segment via the PHP Segment Library

How do we go about achieving this?

**Comment by butterup** [comment]
Here's an illustration of the issue we're facing.

We want to be able to group by iOS and Android only. We don't want users being identified as "Analytics-php"

<img width="1562" alt="analytics-php" src="https://user-images.githubusercontent.com/17927165/99266130-5aa5ad00-281a-11eb-8f9f-22dda271abd6.png">

**Comment by nd4p90x** [comment]
@butterup After reviewing your concern with the other engineers, we suggest using a custom field to report which platform the data is coming from, then you can classify your reports based on that field instead.  The current platform field is a core field that is used across all of our LIBs to determine what LIB the data is coming from, we would not be able to allow the end user to override that field at this time.  Thank you.
