### ISSUE TITLE
Moodle 

### ISSUE THREAD

**Issue by Sydwelll** [segmentio/analytics-php#154]
Any idea on how to plug it to Moodle ?

**Comment by nd4p90x** [comment]
Can you give me more details on which Moodle product you are referring to and what type(s) of data you are wanting to store?  I am familiar with Moodle, just need more information to assist in next steps.  Thanks.

**Comment by Sydwelll** [comment]
Basically, 

i installed a Moodle (3.9.2) instance and i want to link it to my segment sources. I followed the tutorial (about Wordpress) but the files are differents and i don't know how to manage it on Moodle (I'm not a PHP developer).

What i want to store is data about students like the time spent on the platform, the time spent on the videos... data like that.

Thank you for your help and your quick answer

**Comment by nd4p90x** [comment]
@Sydwelll apologies for letting this issue get away from me.  If you still need assistance with implementation, please feel free to re-open this issue and I will do my best to help.  Again, very sorry for the delay in response.
