### ISSUE TITLE
[BUG] Segment::Init delay 10 seconds to initialize

### ISSUE THREAD

**Issue by lucascmelo** [segmentio/analytics-php#155]
The segment PHP library has a bug in its batching code (it is supposed to sleep 10 seconds during a batch push but it doesn't check if it will be doing a batch push). 
![image](https://user-images.githubusercontent.com/881905/106752063-c83acb80-6608-11eb-965d-39531df556a2.png)

I had installed the library and call the Segment::init. 
Every time my WordPress does some action (reload the page, ajax request) delay at least 10 seconds to continue.

I removed this part of the code and the WP work very fast.

Do you know how to fix it? 
![image](https://user-images.githubusercontent.com/881905/106752615-6af34a00-6609-11eb-907b-d4a5de6483b9.png)

Thanks.

**Comment by clmntgr** [comment]
Hey same issue here.
Not sure to understand all the code but maybe you should `usleep` in the loop only when there is still some events to flush? (https://github.com/segmentio/analytics-php/blob/master/lib/Segment/QueueConsumer.php#L157)

**Comment by nd4p90x** [comment]
Based on the default parameters described in the documentation, there is a default wait time of 10 seconds when pushing batches to the server.  If you require a batches to be recorded faster then you are allowed to modify your local options.  The specific option for this would be "flush_interval".  I understand that you are including analytics in your code for "real-time" reporting from a WP site.  I would recommend that you batch your reporting or write to a file so external processes can upload to Segment servers and not affect the functionality of your site.  The reason for this built in delay is so the servers do not get overrun with requests and it eliminates lost records if there is an overrun.  If I am misunderstanding your usage, feel free to re-open this ticket and I will be happy to assist further.

**Comment by clmntgr** [comment]
@nd4p90x the problem is that the `flush` method is called on `__destroy` and it will add a 10s delay (can be reduced to 1s with settings) no matter what, in lambda context this will delay the end of the lambda and in my case the response, why not adding a condition before the delay? If there is no more events to flush there is no need to wait 10s for nothing.

**Comment by nd4p90x** [comment]
@clmntgr Ok, this is perfect.  I have re-opened the issue and will add this to the todo list.  Thank you for your response.
