### ISSUE TITLE
Latest stable version?

### ISSUE THREAD

**Issue by acontia** [segmentio/analytics-php#159]
What is the latest stable version of this package that I can use safely in a project?

I see that the latest tag published is `1.6.1-beta`, from 1st May 2018.

There seems to be work done actively on the `master` and `release/1.6.2` branches, but it is usually not best practice to require a branch.

Any advice?

**Comment by nd4p90x** [comment]
@acontia Thank you for asking this question.  The 1.6.1-beta on master is the branch you should be using.  We have been making significant steps to releasing out of the 1.6.1-beta and should be doing so early next quarter.  Regardless, all new work is being merged into the master branch at this time.  If you have any questions, feel free to ask as we welcome all questions and comments.
