### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by kimpoytoledo** [segmentio/analytics-php#164]
Not sure how to fix the issue but I'm not seeing any updates on my sources. please help.

[Analytics][LibCurl] SSL certificate problem: unable to get local issuer certificate.
![image](https://user-images.githubusercontent.com/8098410/114405264-16f07d00-9bd9-11eb-9450-820670125e2e.png)

**Comment by nd4p90x** [comment]
@kimpoytoledo I just tested this locally using my test suite and I did not run into any communication issues.  I have also confirmed with Engineering that they are not aware of any issues at the moment.  Based on some research, it would appear there may be an issue with your local certs.  Take a look at this resolution to see if it may resolve your issue.  
Thank you.

[Stackoverflow](https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate#:~:text=328-,curl%3A%20(60)%20SSL%20certificate%20problem%3A%20unable,to%20get%20local%20issuer%20certificate&text=If%20this%20HTTPS%20server%20uses,domain%20name%20in%20the%20URL).)
