### ISSUE TITLE
Persist Log File - File Consumer Config

### ISSUE THREAD

**Issue by spencerattick** [segmentio/analytics-php#165]
Is there a way to indicate that the log file (which is automatically deleted once events are sent) should be persisted? It would be great to be able to have that file for customers who want it for retries.

Let me know if you need more info!

**Comment by nd4p90x** [comment]
@spencerattick Thank you for your question.  Currently there is not a way to :save: the file after it is consumed.  I can see where this may be beneficial at times, however, currently the demand for this feature does not warrant the modification at this time.  For your benefit, it isn't as easy as removing or changing the unlink function, there would need to be some thought put into the handling of the file, should it be moved to an archived folder?  What should it be renamed to if anything?  etc, etc.  Thanks again for posting your question we love to see the interactions and how people are using the product.
