### ISSUE TITLE
Modify Endpoint to match API docs

### ISSUE THREAD

**Issue by TristanPouliquen** [segmentio/analytics-php#171]
Hello, 

On the v1.7.0, the URL used for batch actions in LibCurl.php is /v1/import. This URL does not appear in your HTTP API, and has been changed on master since to /v1/batch, that exists in your HTTP API.

Should /v1/import still work? Otherwise, could you make a new release so the SDK relies on the new URLs?

**Comment by nd4p90x** [comment]
Thank you for the question.  Yes, it does still work.  We will be updating this in the near future.
