### ISSUE TITLE
Bug in lib/Segment/Consumer/Socket.php

### ISSUE THREAD

**Issue by TristanPouliquen** [segmentio/analytics-php#172]
Hello,

In [Socket.php](https://github.com/segmentio/analytics-php/blob/6fe929fcdbecb42ecc8964e8b10f35a472f0eb6d/lib/Segment/Consumer/Socket.php#L159), you return a `$success` variable that has never been initialized. 

What should it return? Is it easy to fix?

**Comment by nd4p90x** [comment]
@TristanPouliquen Good catch, we should be returning the successful request response from the server.
