### ISSUE TITLE
usleep in flush() causes unexpected delays on page loads

### ISSUE THREAD

**Issue by fandm** [segmentio/analytics-php#173]
Hi everyone,
Could you please explain why do we need this `usleep` https://github.com/segmentio/analytics-php/blob/e0aef0001b6d3a375341888b7bb98e34de62ecae/lib/Segment/QueueConsumer.php#L157 in the latest version?

The problem is that these **usleep** calls slow down the site performance with the default setting for **10 sec**.
![Screenshot 2021-05-26 at 9 09 08 AM](https://user-images.githubusercontent.com/4036323/119611143-f7b55400-be02-11eb-8571-244ebdb728a6.png)

We set this setting (_flush_interval_) to minimal allowed value **1 sec** but anyway, it causes 1-sec delays on all pages where we have Segment events tracking. 
![Screenshot 2021-05-25 at 11 38 42 PM](https://user-images.githubusercontent.com/4036323/119611522-7611f600-be03-11eb-93f0-9287d5120fd4.png)
And we had no such issues with the previous version of the library.

So, what was the reason for adding these **usleep** calls? Should we use the library some another way now to avoid this issue?

Thanks!

**Comment by nd4p90x** [comment]
I agree that this was missing some extra logic regarding the queue and flushing, which is why the current version does have that added logic.  I am not sure how you found this older version without installing the latest.  Would you mind telling me how you installed your version so I can investigate if there is something amiss. Here is the current reference to that file: 
https://github.com/segmentio/analytics-php/blob/6fe929fcdbecb42ecc8964e8b10f35a472f0eb6d/lib/Segment/QueueConsumer.php#L159

**Comment by fandm** [comment]
Thank you for your response.
We have just tried to use the master branch and don't see now delays related to these usleep calls.
So, we will be waiting for a new release.
Thanks!

**Comment by lmakarov** [comment]
This is a critical bug and the fix needs to be rolled out ASAP.

Our server load and page response times went through the roof after the update (10x):

![image](https://user-images.githubusercontent.com/1205005/119866111-4c270500-bed1-11eb-9bec-45e489130751.png)

We are trying to decide whether we rollback, use master or wait for the next/hotfix release (if that happens any time soon).

@nd4p90x would you be able to provide any timeframe for the next release?

**Comment by nd4p90x** [comment]
Apologies for the delay in releasing the latest.  We have a [PR](https://github.com/segmentio/analytics-php/pull/177) that will update the version to 1.8.0 and which fixes these timing issues.  This should be merged within the next 24hrs.  Until then, I suggest you use the master branch.  Again, sorry for any issues this has caused our consumers.
