### ISSUE TITLE
Performance decrease after update from 1.5 to 1.7

### ISSUE THREAD

**Issue by yari-dev** [segmentio/analytics-php#178]
The update from 1.5.2 to 1.7.0 has caused a major performance decrease in our page load time, up to 10 seconds on top of the original load time.

**Comment by lmakarov** [comment]
yeah... see https://github.com/segmentio/analytics-php/issues/173

**Comment by nd4p90x** [comment]
@yari-dev Thank you for your comments, I apologize for the issues with timing that you are seeing.  There is a fix in the master branch and we have a PR in for a new release with new features which includes this update.  We should have the new version, 1.8.0, released within the next 24hrs.
