### ISSUE TITLE
Undefined index: type in segmentio/analytics-php/send.php on line 75

### ISSUE THREAD

**Issue by faridmovsumov** [segmentio/analytics-php#179]
I am getting the following error. Could you please help me understand why?

Version: 1.7.0

```
PHP Notice:  Undefined index: type in /var/www/public_html/vendor/segmentio/analytics-php/send.php on line 75
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, second array member is not a valid method in /var/www/public_html/vendor/segmentio/analytics-php/send.php on line 76
```

**Comment by nd4p90x** [comment]
@faridmovsumov Thank you for your question.  It would appear that the index "type" is  missing from your array.  Could I ask how you called the analytics method?  Below is an example and the resulting data that is sent to the Segment servers for processing based on the type of data being sent:

(In-line script)
```
analytics.track(user_id: 13, event: 'Login')
analytics.identify(user_id: 13,
                   traits: {
                     email: 'sduvall@mark4tech.com',
                     name: 'Shane Duvall',
			timestamp: '2021-05-29T10:36:27.036621-05:00'
                   })
```

OR (an example from my Laravel Project)

```
        Segment::identify([
            'userId' => $this->userID,
            'traits' => [
                'name' => $this->name,
                'email' => $this->email,
            ],
        ]);

        Segment::track([
            'userId' => $this->userID,
            'event' => $this->url,
            'properties' => [
                'email' => $this->email,
            ],
        ]);       

        Segment::flush();
```

These event types then generate the following JSON for processing:
type = "TRACK":

_{
  "context": {
    "library": {
      "consumer": "LibCurl",
      "name": "analytics-php",
      "version": "1.7.0"
    }
  },
  "event": "Login",
  "integrations": {},
  "messageId": "e603278f-a375-462e-96a5-f41e61997dac",
  "originalTimestamp": "2021-05-29T10:36:27+00:00",
  "properties": {
    "email": "sduvall@mark4tech.com"
  },
  "receivedAt": "2021-05-29T10:36:27.036Z",
  "sentAt": "2021-05-29T10:36:27.000Z",
  "timestamp": "2021-05-29T10:36:27.036Z",
  "type": "track",
  "userId": "13",
  "writeKey": "*********************"
}_

type= "IDENTIFY":

_{
  "context": {
    "library": {
      "consumer": "LibCurl",
      "name": "analytics-php",
      "version": "1.7.0"
    }
  },
  "integrations": {},
  "messageId": "0418b7ca-92dd-4a7d-96a2-7cb130f4499f",
  "originalTimestamp": "2021-05-19T17:25:34+00:00",
  "receivedAt": "2021-05-29T10:36:27.036Z",
  "sentAt": "2021-05-29T10:36:27.000Z",
  "timestamp": "2021-05-29T10:36:27.036Z",
  "traits": {
    "email": "sduvall@mark4tech.com",
    "name": "Shane Duvall"
  },
  "type": "identify",
  "userId": "13",
  "writeKey": "*********************"
}_

**Comment by nd4p90x** [comment]
@faridmovsumov Morning, can we assume that these notices and warnings are related to the file issues you and I have discussed offline?  If you think they are not, then please feel free to re-open the issue and we can pursue it further.  Thank you.
