### ISSUE TITLE
v1.8 does not send `track` event

### ISSUE THREAD

**Issue by WhereJuly** [segmentio/analytics-php#180]
Hello colleagues,

I have used the `segmentio/analytics-php` package since v1.5 for some months now. I have had v1.7 in `dev` and `stage` environments. That sends the `track` event well.

In `production` environment since several days no `track` events goes out of my application. This happened after `segmentio/analytics-php` package was updated to v1.8. a couple of days ago.

No change in the package intialization or Segment event sending code hase been made since months. At the same time the code is the same across the environments. The Segment write code is the same for all environments.

To recap: my `dev` and `stage` environments have `segmentio/analytics-php`  v1.7. They send the `track` events well. The `production` environment with v1.8 does not send the `track` event.

Now as I upgrade my `dev` and `stage` environments up to v1.8 no `track` event goes out of my application.

v1.8 is not a breaking change so I would not expect it would not work because the initialization or event send mechanics change. The release description is empty so no chance to see what has changed.

Besides I the would the package would have thrown the exceptions or signal in some other way that I call it in an incorrect way.

However it just silently does not send `track` event.

While I can fix my problem by downgrading to v1.7 I suspect for v1.8 there is a clear sign of the issue.

**Comment by nd4p90x** [comment]
@WhereJuly Thank you for pointing this out.  We will investigate this issue and get back with you asap.

**Comment by nd4p90x** [comment]
@WhereJuly Hello, I am actively testing this issue you have presented.  I always try to test in multiple ways before I respond since there are many ways to implement the library.   Currently I have tested via straight up scripting, using laravel via the analytics object and via the internal queue process and I am unable to reproduce loss of "track" events.  Can you please provide my with the type of implementation you are using and without divulging any proprietary data, can you provide me a snippet of your code which builds out the Segment::track object?  I want to do my best to duplicate your setup while testing.  Thank you.

**Comment by WhereJuly** [comment]
Hi @nd4p90x,
I use Segment via composer. I do it as described in the [original Segment PHP docs](https://segment.com/docs/connections/sources/catalog/libraries/server/php/).

I initialize Segment like this:
``` php
class_alias('Segment', 'Analytics');
\Segment::init(MY_WRITE_KEY_HERE);
```

Then I call the `track` event like this: `\Segment::track($payload)` where payload is the data structure as per [this gist](https://gist.github.com/WhereJuly/13805620ee50384df4b82b4ed74b25e7) (see both the payload creation code and the actual depersonalized payload data copied from Segment debugger).

**Comment by nd4p90x** [comment]
@WhereJuly Thanks for the information, I will attempt to build out my object similarly.  Can I assume that the JSON from the Segment Debugger you provided is from your functioning implementation using v1.7 and not the failing v1.8?

**Comment by nd4p90x** [comment]
@WhereJuly [Here](<script src="https://gist.github.com/nd4p90x/f01022f84744fdbd746f9df635bb48de.js"></script>) is the payload and RAW response that I get using your data in the array, (Hardcoded of course).  I know this does not exactly help you, but just so you can see that I am using the latest, via composer in my Laravel test project, and I am getting what is expected.  I will continue to work on this for the time being, however, if I am unable to duplicate the issue, I am not sure what the next steps are for me to help resolve your issue.

**Comment by WhereJuly** [comment]
@nd4p90x I see. Thanks for investigation. I will keep v1.7 for the time being. Just close the issue then if you cannot repeat my error. Thanks again.

**Comment by nd4p90x** [comment]
@WhereJuly My apologies for not being able to assist you more with the issue.  I will keep this issue in the forefront, just in case others customers see the same thing.  So far, I have not heard of any others with this issue using v1.8.0.  If you do find a solution or a cause, please open a new ticket or re-open this one.  Thanks again.
