### ISSUE TITLE
Socket TLS option

### ISSUE THREAD

**Issue by dsalyards** [segmentio/analytics-php#184]
Hi,

I am looking into using your library but looks like your connection via php Sockets doesn't support TLS, see https://www.php.net/manual/en/transports.inet.php. This seems like an easy fix to check if a new option is set here https://github.com/segmentio/analytics-php/blob/0048caedf87b9019f2588aadd1d8dd7a6d9c5abb/lib/Segment/Consumer/Socket.php#L56

`if ($this->options["tls"]) { $protocol = 'tls'; }`

**Comment by nd4p90x** [comment]
I will look into this and implement soon, thank you.
