### ISSUE TITLE
Lib_curl configure timeouts

### ISSUE THREAD

**Issue by dsalyards** [segmentio/analytics-php#185]
Hi, I am looking into using your library, but your lib-curl doesn't support custom values for 
CURLOPT_TIMEOUT
CURLOPT_CONNECTTIMEOUT
would you consider adding option checks for timeOut and connectionTimeOut to https://github.com/segmentio/analytics-php/blob/0048caedf87b9019f2588aadd1d8dd7a6d9c5abb/lib/Segment/Consumer/LibCurl.php#L60 so these values could be set?

**Comment by nd4p90x** [comment]
I will look into this and implement soon, thank you.
