### ISSUE TITLE
Laravel integration question

### ISSUE THREAD

**Issue by Synchro** [segmentio/analytics-php#189]
There is a Laravel wrapper for the analytics-php library [here](https://github.com/AltThree/Segment), with an updated fork [here](https://github.com/MatanYadaev/Segment/tree/support-php-8) for PHP 8 support. The maintainer of this package has [mentioned that they are not keen on continuing to maintain it](https://github.com/AltThree/Segment/issues/21#issuecomment-662054001). Would you be willing to take it on? I know it could be considered the "thin end of the wedge" from a support point of view, but I certainly prefer to use "official" libraries when interacting with a commercial service, and it would be a nice addition (given Laravel's popularity) if you have the bandwidth.

Just a thought.

**Comment by nd4p90x** [comment]
@Synchro This is a great idea, I will discuss it with the team and let you know.  Thank you
