### ISSUE TITLE
Vendor/autoload.php is not found

### ISSUE THREAD

**Issue by ankitjdepoint** [segmentio/analytics-php#190]
Hi,

I might sound silly to you, but I cloned the library but I do not see any vendor folder with it, which is required in bin/analytics file.

Please update me about it.

FYI: I am trying to resolve this issue "syntax error, unexpected 'Client' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)"

Thanks,
Ankit

**Comment by nd4p90x** [comment]
@ankitjdepoint Morning, I could assist with your implementation if you could provide me with some snippets.  The vendor autoload should not cause you to not be able to instantiate the class and use the functions, nor should it cause a syntax error in your code.  Thanks

**Comment by nd4p90x** [comment]
@ankitjdepoint if you need further assistance, feel free to re-open this issue or open a new one.  Thank you.
