### ISSUE TITLE
Make `max_queue_size_bytes` and `max_item_size_bytes` configurable

### ISSUE THREAD

**Issue by ptondereau** [segmentio/analytics-php#196]
IS there any reason to not let end user configure `max_queue_size_bytes` or `max_item_size_bytes`  from the options array?
If not, I can submit a PR.

Line: https://github.com/segmentio/analytics-php/blob/cc499e6eb16d3ce0635b21fafc76b6ba58d47e99/lib/Consumer/QueueConsumer.php#L19

**Comment by nd4p90x** [comment]
@ptondereau These maximums are determined by the Segment servers and APIs.  They are not consumer modifiable.

**Comment by ptondereau** [comment]
I'm not confident with your answer because I've forked this repo and tried to increase this limit and it went well on the API's response(sent a 46kb payload). 
So my question is are you very sure about this statement?

**Comment by nd4p90x** [comment]
@ptondereau I am confident in my statement.  The fact that you are able to send more than prescribed by the design, does not mean that you can or should.  You will eventually have dropped transactions and they will be lost in the ether forever.  This setting is uniform across all of the LIBs that Segment has built for their customers.  I would ask that you don't go outside the limits of the system for this very reason.  If you have any other questions or concerns, please feel free to contact us.  Comments and interactions from our customers are always welcome, and help us to better our products for users like you.  Thank you.
