### ISSUE TITLE
v1.8/v2.0 Class 'Segment' not found

### ISSUE THREAD

**Issue by bobbyatsegment** [segmentio/analytics-php#199]
Had a customer write in about seeing `Class 'Segment' not found` when trying to run a simple setup. I was able to recreate the same with a similar error. 

Here's what the customer sent in using v1.8:
```

class_alias('Segment', 'Analytics');
Segment::init($_SESSION['segment_KEY']);

The init command gets this error:
Severity: Warning

Message: Class 'Segment' not found

Filename: controllers/Configure.php

Line Number: 135
```

Here's the code I'm using with v2.0:

```
<?php
require_once("analytics-php/lib/Segment.php");

# set up our Segment tracking and
# alias to Analytics for convenience
class_alias('Segment', 'Analytics');
Segment::init("mywritekey");

echo "Start\n";

?>
```

Produces this error:

Parse error: syntax error, unexpected 'Client' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /analytics-php/lib/Segment.php on line 9

I tried downgrading to v1.7 (as suggested [here](https://github.com/segmentio/analytics-php/issues/180)) and was able to run the script with no issues.

**Comment by nd4p90x** [comment]
@bobbyatsegment 

The latest version require the new namespace calls:  https://segment.com/docs/connections/sources/catalog/libraries/server/php/#getting-started

```
require_once("/path/to/analytics-php/lib/Segment.php");
use Segment\Segment;
```

Please let me know if this does not work for you and I will investigate further.

Thank you

**Comment by bobbyatsegment** [comment]
Hi @nd4p90x thanks for the quick reply!

I can confirm it still produces the same error for me with the namespace call in place

**Comment by nd4p90x** [comment]
I will give it a test and let you know what I find, Thank you

**Comment by nd4p90x** [comment]
Version 1.8 Test was successful using:
```
<?php
require_once("./lib/Segment.php");
# set up our Segment tracking and
# alias to Analytics for convenience
class_alias('Segment', 'Analytics');
Segment::init("**********************", array( 
  "debug"=>true,    
  "max_queue_size" => 10000,
  "flush_at"     => 100
));

Segment::identify(array(
  "userId" => "mark4tech01",
  "traits" => array(
    "email" => 'shane@northtwofive.com',
    "name" => 'Shane Duvall',
    "friends" => 2
  )
));
Segment::page(array(
  "userId" => "mark4tech01",
  "category" => "website",
  "name" => "Mark 4 Technologies",
  "properties" => array(
    "url" => "https://www.mark4tech.com"
  )
));

  Segment::track(array(
    "userId" => "mark4tech01",
    "event" => "Article Bookmarked:1",
    "properties" => array(
      "title" => "Snow Fall:1",
      "subtitle" => "The Avalanche at Tunnel Creek:1",
      "author" => "John Branch:1",
      "datetime" => date("Y-m-d H:i:s")
    )
  ));

    Segment::track(array(
    "userId" => "mark4tech01",
    "event" => "Article Bookmarked:2",
    "properties" => array(
      "title" => "Snow Fall:2",
      "subtitle" => "The Avalanche at Tunnel Creek:2",
      "author" => "John Branch:2",
      "datetime" => date("Y-m-d H:i:s")
    )
  ));

Segment::flush();

?>
```

**Comment by nd4p90x** [comment]
Hopefully the latter test help more:

Version 2.0 Test was successful using:

```
<?php

require_once __DIR__ . "/lib/Segment.php";

use Segment\Segment;

...same objects as used in 1.8 test...
?>
```

I used your exact code and received errors due to location of the lib on my filesystem, once I updated that I was successful at reporting my object:

```
<?php
require_once __DIR__ . "/lib/Segment.php";

use Segment\Segment;

//require_once("analytics-php/lib/Segment.php");

# set up our Segment tracking and
# alias to Analytics for convenience
class_alias('Segment', 'Analytics');
Segment::init("**************");

echo "Start\n";

Segment::identify(array(
  "userId" => "mark4tech01",
  "traits" => array(
    "email" => 'shane@northtwofive.com',
    "name" => 'Shane Duvall',
    "friends" => 2
  )
));
?>
```
Result as shown in Segment.io debug:
```
Raw:
Analytics::identify(array(
  "userId" => "mark4tech01",
  "traits" => array(
    "email" => "shane@northtwofive.com",
    "friends" => 2,
    "name" => "Shane Duvall"
  )
));
```

**Comment by bobbyatsegment** [comment]
Thanks for the update, I tried using the snippet you sent for v2.0 and am still experiencing the same error. It keeps directing me to `private static Client $client;` on Line 9 being problematic in Segment.php:

![syntax_error_line](https://user-images.githubusercontent.com/93934274/153059853-fa8b40d0-a0f3-40b3-9db1-0f4c73956666.png)

**Comment by nd4p90x** [comment]
That looks like version 3.0.0 to me.  Something is not right there, looks like a release may have been overlooked and 3.0 is still labeled 2.0.0.

Here is how I implemented that version:

```
#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace hello;

use Segment\Segment;
use Segment\SegmentException;

require 'lib/Segment.php';
require 'lib/Client.php';
require 'lib/SegmentException.php';
require 'lib/Consumer/Consumer.php';
require 'lib/Consumer/QueueConsumer.php';
require 'lib/Consumer/LibCurl.php';

# set up our Segment tracking and
Segment::init("**********", array( 
  "debug"=>true,    
  "max_queue_size" => 10000,
  "flush_at"     => 100,
  "tls"=>true,
  "curl_timeout" => 10,
  "curl_connecttimeout" => 10
));

Segment::identify(array(
  "userId" => "mark4tech01",
  "traits" => array(
    "email" => 'shane@northtwofive.com',
    "name" => 'Shane Duvall',
    "friends" => 2
  )
));
```

**Comment by bobbyatsegment** [comment]
Oh, good catch! Confirming the version is actually 3.0.0 However, using that implementation doesn't change the error from Segment.php Line 9

**Comment by nd4p90x** [comment]
Hmmmmm.  Not sure what is going on with your implementation.  Starting to sound like something with a path or the location of the analytics-php install.  Here is my test using your snippet above with successful results sent to the segment servers:

```
#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace hello;

use Segment\Segment;
use Segment\SegmentException;

require 'lib/Segment.php';
require 'lib/Client.php';
require 'lib/SegmentException.php';
require 'lib/Consumer/Consumer.php';
require 'lib/Consumer/QueueConsumer.php';
require 'lib/Consumer/LibCurl.php';

Segment::init("***************");

echo "Start\n";

Segment::identify(array(
  "userId" => "mark4tech01",
  "traits" => array(
    "email" => 'shane@northtwofive.com',
    "name" => 'Shane Duvall',
    "friends" => 2
  )
));

?>
```

**Comment by bobbyatsegment** [comment]
Interesting! I'm by no means an expert with php, can the location of where I installed analytics-php affect how VSCode interprets a syntax error?

Could you verify what your Client.php Line 15 looks like, and what Segment.php Line 9 looks like in your working 3.0.0 implementation?

**Comment by nd4p90x** [comment]
Yes, the location of the LIBs source is relevant here.  You may need to adjust the pathing within your code to match your install location.  I'm sure that is probably all it is at this point.

As you requested:
Client.php:
```
<?php

declare(strict_types=1);

namespace Segment;

use Segment\Consumer\Consumer;
use Segment\Consumer\File;
use Segment\Consumer\ForkCurl;
use Segment\Consumer\LibCurl;
use Segment\Consumer\Socket;

class Client
{
    protected Consumer $consumer;

```
Segment.php:
```
<?php

declare(strict_types=1);

namespace Segment;

class Segment
{
    private static Client $client;

```

**Comment by bobbyatsegment** [comment]
I don't believe this is a pathing error, it says "No such file or directory" if the libs source is not being accessed. When the path is correct, the file is accessed, but Line 9 fails for each Lib source

I did a fresh clone into a folder on my desktop and created an index.php with the script you provided and am still getting the same results. Three Success Engineers went about this process and encountered the same error:

`Parse error: syntax error, unexpected 'Client' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /analytics-php/lib/Segment.php on line 9`

However, with the same directory structure, version 1.7 works without fail

**Comment by nd4p90x** [comment]
@bobbyatsegment let me take a fresh look tomorrow by pulling down everything into a new folder and starting from there.

**Comment by Steven5678231** [comment]
Same problems here, can confirm path is correct cuz I am using require_once(WP_PLUGIN_DIR . '/analytics-php/lib/Segment.php'); and I put the segment folders into the wp-content/plugins/ folder.
