### ISSUE TITLE
Batch size checking is 32KB instead of 500KB

### ISSUE THREAD

**Issue by Liamso** [segmentio/analytics-php#200]
Batch size checking is 32KB instead of 500KB in 

/Segment/Consumer/ForkCurl.php & 
/Segment/Consumer/Socket.php 

The docs specify that the payload can be up to 500kb but that each operation shouldn't exceed 32kb.

**Comment by arnaud-lb** [comment]
Related: https://github.com/segmentio/analytics-php/issues/196
