### ISSUE TITLE
Timeline for next release

### ISSUE THREAD

**Issue by chrismeyers** [segmentio/analytics-php#204]
Hello!

I was wondering if there are any plans for the next release of this library?  If so, is there a general timeline for when we can expect the release?  It's been a little over a year since the v2.0.0 release and it looks like there have been quite a few changes since then.

We're integrating this library into an internal wrapper library at our company and have run into some inconsistencies with the latest release.  It looks like most of these problems have been fixed, they just haven't been released yet.  For example, the return value from the `LibCurl::flushBatch()` method unexpectedly returns an integer response code in [v2.0.0](https://github.com/segmentio/analytics-php/blob/2.0.0/lib/Segment/Consumer/LibCurl.php#L113), but it correctly returns a boolean in the current [HEAD](https://github.com/segmentio/analytics-php/blob/5ee62a163dfea0bccbf185f613f32564777bc063/lib/Consumer/LibCurl.php#L98).

Any updates would be greatly appreciated, thanks!

**Comment by nd4p90x** [comment]
@chrismeyers We are in the process of generating a new release, should be completed within the next few days.  Thank you.

**Comment by adimmitt** [comment]
Was hoping to know if you have an update to this issue so we can use the updated version in our code. Thanks again for the help.

**Comment by nd4p90x** [comment]
@adimmitt sorry for the delay, I will work on that today and we should have a new release by tomorrow.

**Comment by pooyaj** [comment]
Just released 3.5.0 💥
