### ISSUE TITLE
Start testing on PHP 8.1 and more importantly: 8.2

### ISSUE THREAD

**Issue by ruudk** [segmentio/analytics-php#210]
CI only runs PHP 7.4 and 8.0.

**Comment by nd4p90x** [comment]
We will begin to look into 8.1 testing, since 8.2 is so new, we may look into testing against 8.2, but it is not a priority at this time.  

Thank you

**Comment by ruudk** [comment]
> since 8.2 is so new, 

Unbelievable. Step up your game.

**Comment by Synchro** [comment]
Something to tell your management if they need some incentive – we have had to temporarily disable our segment integration because of this issue.

**Comment by ruudk** [comment]
PHP has been released on November 24, 2022. It's now March 9, 2023. At the end of this year, PHP 8.3 will be released.

**Comment by Synchro** [comment]
FWIW, I'm an open source maintainer, and I've been testing my packages on 8.3 development builds since December; libraries need to be ahead of PHP releases.

**Comment by Synchro** [comment]
Great news that you've merged that PR, thank you

**Comment by Synchro** [comment]
Please could you tag a release for this? Otherwise we can't get at it through composer updates.
