### ISSUE TITLE
Request timeouts for consumers are too long

### ISSUE THREAD

**Issue by roborourke** [segmentio/analytics-php#214]
Hi, I've recently encountered a problem when the Segment API was slow to respond. For this kind of workload the timeouts would ideally have a good default of 5s, maybe less. From what I can gather in the code the curl requests have an unlimited timeout, and a connect timeout of 300s. There is a retry & backoff routine however if the first request is the one that takes a long time it can cause a huge performance issue. In my case PHP will timeout after 30s.

**Comment by nd4p90x** [comment]
@roborourke regarding managing timeouts, you are more than welcome to override these settings by setting the flush_interval, curl_timeout and curl_connecttimeout in your init object.  Let me know if I can assist in any other way.  
Thanks
