### ISSUE TITLE
Class Segment  not found

### ISSUE THREAD

**Issue by ikolosis** [segmentio/analytics-php#228]
Good day everyone, I just downloaded this **php analytics** and I want to try it out for the first time.    Am trying to run the code  below but it triggers error.  Please why am I getting this error can someone give me a working sample solution to enable me send my segment identity data. its urgent.  Thanks

```

Warning: Class "Segment" not found in C:\xampp\htdocs\twilio_segment\index.php on line 7

Fatal error: Uncaught Error: Class "Segment\Client" not found in C:\xampp\htdocs\twilio_segment\analytics-php\lib\Segment.php:20 Stack trace: #0 C:\xampp\htdocs\twilio_segment\index.php(8): Segment\Segment::init('CmKLLB7L...') #1 {main} thrown in C:\xampp\htdocs\twilio_segment\analytics-php\lib\Segment.php on line 20

```

Here is the code
```

<?php
require_once("analytics-php/lib/Segment.php");
use Segment\Segment;

//Set up our Segment tracking and
//alias to Analytics for convenience
class_alias('Segment', 'Analytics');
Segment::init("my key goes here");

echo "welcome to segment";

Segment::identify(array(
  "userId" => "f4ca124298",
  "traits" => array(
    "name" => "Michael Brown",
    "email" => "mbrown@example.com"
  )
));



```

?>

**Comment by nd4p90x** [comment]
@ikolosis Hello,
I am unable to reproduce your results with my setup.
Have you had any luck moving past this issue?  I will try a few more test instances to see if I can reproduce elsewhere.

Thanks,
