### ISSUE TITLE
Ongoing changes for API v2

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/analytics-php#27]
https://github.com/segmentio/spec

- [x] Use HTTP Basic Auth with the project's **Write Key**.
- [x] Rename to `anonymousId` from `sessionId` for clarity.
- [x] Separate `integrations` (was `providers`) object from `context`, for cleaner logs.
- [x] Add `messageId` for easily tracing calls through to the raw logs.
- [x] Change `library` to be a object with `name` and `version` for consistency.

**Comment by jbrooksuk** [comment]
If you rename `anonymousId` to `sessionId` please make sure you bump the major version as that's script breaking for Cachet.

**Comment by calvinfo** [comment]
Ah good call! This was actually closed with version 1.0.0, but looks like we forgot to close out the issue. We'll keep `anonymousId` going forward.

**Comment by jbrooksuk** [comment]
Thanks!
