### ISSUE TITLE
zendesk ticket feedback

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/analytics-php#42]
1) Your docs for the PHP installation say to run this for simplicity:

Setup our Segment tracking and alias to Analytics for convenience

`class_alias('Segment', 'Analytics');`
`Analytics::init("YOUR_WRITE_KEY");`

Why not just include this in your repository?

`require_once 'Segment.php';class Analytics extends \Segment {}`

2) Your code repository doesn’t seem very composer-compliant. I’m no expert on composer, but usually adding something like

"Analytics\\": "vendor/segmentio/analytics-php/lib/"

To the composer.json “autoload” section will let me do a “use Analytics” on my php file instead of a “require_once …”. I noticed no namespaces were being used in the classes.

**Comment by lewilewilewi** [comment]
Just want to bump this as it hasn't been dealt with in quite a long time, and it's not solved - I'm in the middle of integrating the libraries with my companies systems and using namespaces and autoload would have made my task significantly easier.
