### ISSUE TITLE
Laravel 4 wrapper

### ISSUE THREAD

**Issue by jbrooksuk** [segmentio/analytics-php#47]
I don't know if it's of any use to you guys, but I wrote a wrapper package for Laravel 4, with L5 support coming soon.

**Comment by calvinfo** [comment]
Oh awesome. If you have instructions and a link, we'll add it to our docs!

cc @DirtyAnalytics

**Comment by jbrooksuk** [comment]
https://github.com/cachethq/Laravel-Segment

All the docs you need are in the README.

**Comment by calvinfo** [comment]
Sweet! We'll get it added
