### ISSUE TITLE
File consumer ignores integer timestamps

### ISSUE THREAD

**Issue by gwlortscher** [segmentio/analytics-php#48]
The 'File' consumer appears to ignore timestamps when loading historical events using "track".

Using the Socket consumer and an example timestamp of 1396594800, the below code correctly sends (and Segment receives) an event with a timestamp of "2014-04-04T07:00:01.939Z".

But using the File consumer, the exact same code results in Segment receiving a timestamp of "now". 

```
Analytics::track([
	'userId' => 100,
	'event' => 'Sent Message',
	'timestamp' => 1396594800
]);
```

Interestingly, the analytics.log file does seem to contain a correct timestamp of "2014-04-04T00:00:00-07:00", but when parsed and sent using send.php, it arrives at Segment as "now".

**Comment by gwlortscher** [comment]
It looks like the addition of microtime support in 1.1.0 broke the ability to use integer timestamps with the File consumer. In particular, see this line of send.php:

```
$ts = floatval($dt->getTimestamp() . "." . $dt->format("u"));
```

This is casting integer timestamps as doubles, which is throwing off the formatTime() method of Segment_Client. Confirmed this by modifying as follows, which got integer timestamps working again:

```
$ts = $dt->getTimestamp();
```

Switching to 1.0.3 works for now.

**Comment by calvinfo** [comment]
Ah sorry about that, it looks like you're right! We'll get that fixed up! cc @yields

**Comment by yields** [comment]
@gwlortscher can you try 1.1.3? the issue should be fixed there.
