### ISSUE TITLE
File consumer silently loses events while processing

### ISSUE THREAD

**Issue by gwlortscher** [segmentio/analytics-php#49]
It appears that any new events being written while the file consumer is processing the current backlog via send.php are silently (and completely) lost.

I set a cron job to run every few minutes as recommended in the docs and began processing a large backlog of events. Any new events that occurred while send.php was running were completely lost (as indicated by the dips in the chart below):

![screenshot 2015-02-28 12 46 34](https://cloud.githubusercontent.com/assets/4160947/6428073/2fc02b2e-bf48-11e4-8e5f-4450a538477d.png)

**Comment by calvinfo** [comment]
cc @yields, any idea what's going on here?
