### ISSUE TITLE
missing success/failure feedback in events

### ISSUE THREAD

**Issue by Possum3D** [segmentio/analytics-php#56]
Hi there,

We are using the php client to send data to segment. In order to make sure that events are sent, we are using a message pattern software (kafka). the way it works is:
event -> message in kafka -> track -> if issue, re-track, otherwise move to next message

however, it seems that some events are still missing. after rapid investigation, part of the problem seems to be that enqueue method [Queue Consumer] is returning true if flush was called. This method is called for each track event. However, it does not return the success state of the flush method! therefore, this return value cannot and should not be used as an indicator to know if the operation succeeded.

It might be better to return directly the success state here. 

```
  protected function enqueue($item) {
    $count = count($this->queue);
    if ($count > $this->max_queue_size)
      return false;
    $count = array_push($this->queue, $item);
    if ($count > $this->batch_size)
      $this->flush();
    return true;
  }
```

might become

```
  protected function enqueue($item) {
    $count = count($this->queue);
    if ($count > $this->max_queue_size)
      return false;
    $count = array_push($this->queue, $item);
    if ($count > $this->batch_size)
      return $this->flush();
  }
```
or give some other way to know which of the batch items could not be sent when using track.

Best,

**Comment by hankim813** [comment]
I'll close this based on the date of the issue. Please let me know if this is still an issue and I'll reopen!
