### ISSUE TITLE
Clever solutions, but multiple streams is already implemented in core PHP.

### ISSUE THREAD

**Issue by grahamc** [segmentio/analytics-php#7]
Check into:  http://php.net/manual/en/function.curl-multi-init.php

**Comment by lewilewilewi** [comment]
There's an issue with persistent sockets (I think when the socket is closed server-side, but I'm not sure) - I'm getting the following error:

fwrite(): SSL: Broken pipe

Trace:
0 - at phpErrorHandler() in  on line 
1 - fwrite() in /.../segmentio/analytics-php/lib/Segment/Consumer/Socket.php on line 91
2 - at Segment_Consumer_Socket::makeRequest() in /.../segmentio/analytics-php/lib/Segment/Consumer/Socket.php on line 38
3 - at Segment_Consumer_Socket::flushBatch() in /.../segmentio/analytics-php/lib/Segment/QueueConsumer.php on line 124
4 - at Segment_QueueConsumer::flush() in /.../segmentio/analytics-php/lib/Segment/QueueConsumer.php on line 29
5 - at Segment_QueueConsumer::__destruct() in /.../segmentio/analytics-php/lib/Segment/Client.php on line 44
6 - at Segment_Client::__destruct() in  on line

This is occurring approximately once every 2 or 3 attempts.

**Comment by hankim813** [comment]
I'll close this based out date of the issue. Please reopen if it's still affecting your use of the library!

**Comment by onassar** [comment]
I still run into this every now and then. Probably once a week, a call bails.
