### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by bjornbos** [segmentio/analytics-php#71]
I'm getting the following curl error when trying to send events using the SDK:
"SSL certificate problem: self signed certificate in certificate chain"

**Comment by calvinfo** [comment]
Hmm, that's odd... mind specifying more info about what os you're running on?

**Comment by calvinfo** [comment]
None of the certs in the keychain are self-signed, but it's possible that the client could give errors if it's not picking up certain root certs.

**Comment by f2prateek** [comment]
I think the PHP client should pick up the root certs for us, so it seems like an issue with the host the program is running on; unless I'm missing something.

@bjornbos if you could send us more details on how to reproduce this issue, that would help!

I'm closing this for now, as there isn't a clear action to take.
