### ISSUE TITLE
Question: Blocking calls?

### ISSUE THREAD

**Issue by outrunthewolf** [segmentio/analytics-php#81]
Quick question.

Does the analytics-php SDK use blocking calls? 

**Our use case:**

 - Track every API request a user makes

If the request to send the tracking information to Segment is blocking, ideally we'd wrap the track function in a "shutdown" clause, so that our API response is sent back to the user, before we try and send the tracking information to Segment.

I'd love some idea of whether we need to do this or not?

**Comment by f2prateek** [comment]
@outrunthewolf sorry for the late reply, but the library itself is non blocking.

also for the future, emailing our support team will likely get you a quicker response! https://segment.com/help/contact

We try to stay on top of Github issues but it's easier for us to miss issues :(
