### ISSUE TITLE
context.library not set when context field already exists in message

### ISSUE THREAD

**Issue by bvukas** [segmentio/analytics-php#88]
context.library is added only if context field is not set in message: https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Client.php#L180

Shouldn't the result of `$this->getContext()` be merged with the context sent in the message:

```PHP
    if (!isset($msg["context"])) {
      $msg["context"] = array();
    }
    $msg["context"] = array_merge($msg["context"], $this->getContext());
```

**Comment by arthens** [comment]
Just ran into the same problem. Any update?
