### ISSUE TITLE
Doesn't pass events in Google Analytics

### ISSUE THREAD

**Issue by reyphilipregis** [segmentio/analytics-php#90]
Hi guys, just want to ask how come my code doesn't get logged in Google Analytics? We have integrated Mixpanel, Intercom and Active Campaign using this analytics-php library and its working but in Google Analytics it doesn't work. Thanks.

**Comment by f2prateek** [comment]
Sorry for the delay here. It would be best to direct support questions (especially about integrations to https://segment.com/contact). It's hard to say without more details, but the most common issue is that your GA keys aren't setup properly - our support agents will be able to help you figure it out if you still have this issue.
